baseURL = "https://keimoriyama.github.io/"
languageCode = "jp-JP"
title = "K's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

# [markup]
#   [markup.goldmark]
[markup.goldmark.renderer]
      unsafe = true
      
[params]
  author = "Kei Moriyama"
  description = "D1 @babalablab"
  github = "keimoriyama"
  # facebook = ""
  twitter = "moriy4ma"
  # linkedin = ""
  # instagram = ""
  # tumblr = ""
  email = "kei_moriyama@icloud.com"
  url = "https://keimoriyama.github.io/portfolio/"
  keywords = "blog, google analytics"
  # rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Japan"
  userStatusEmoji = "ðŸ˜€"
  enableGitalk = false
  enableSearch = true
  
[[params.self]]
  name = 'Self'
  url="introduction/introduction"

[[params.projects]]
  name='Projects'
  url="projects/projects"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

